FROM gradle:7.4.2-jdk11 as builder
COPY . /home/gradle/
RUN mkdir /app && \
    cd /home/gradle && \
    gradle build --no-daemon

FROM azul/zulu-openjdk-alpine:13.0.3
RUN mkdir /app
COPY --from=builder /home/gradle/build/libs/*.jar /app/metrics-app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/metrics-app.jar"]